### PR TITLE
Upgrade to 1.20.0

### PR DESCRIPTION
**Pull request by LostLuma**
Hey, since this is one of the few mods I use I thought I'd update it to work in 1.20.0!

- Update HudInfoRenderer for 1.20.0
- Upgraded dependencies (Gradle, Loom, ModMenu, Cloth Config)
- Added [machete](https://github.com/SilverAndro/Machete) to the build script to compress output
- Add Minecraft as a dependency so the game will not start with eg. Minecraft 1.19.4
- Removed LazyDFU from dev env, as it's no longer updated thanks to performance improvements from Mojang

As I've not worked on a Fabric mod using Quilt mappings before I'm not sure whether I've upgraded the `build.gradle` the "correct" way, however it does build the mod perfectly fine.

### CODE REVIEW

**Comment by juliand665** [comment]
Oh, you are an absolute godsend—thank you for doing this again! I'll try to take a look tomorrow, then merge & release :)

**Comment by arnokeesman** [comment]
I get a crash in singleplayer, [crash report](https://mclo.gs/4WDPSbe) [latest.log](https://mclo.gs/THcur1H). Also tried with modmenu and clothconfig installed, didn't help. Though they don't seem related to the issue looking at the logs anyway.
If there's anything else I can provide to help debug this, don't hesitate to ask.

**Comment by LostLuma** [comment]
That crash is what this PR fixes, you're running the Dynamic FPS 2.2.0 for 1.19.4.
If you'd like to test out this PR for 1.20.0 I've uploaded a locally built jar here: https://files.lostluma.net/dynamic-fps-2.3.0.jar

**Comment by arnokeesman** [comment]
okay yeah that's totally my bad, did grab from your repo, just not the correct branch, woops

**Comment by juliand665** [comment]
Just got around to trying it—works like a charm! Thank you so much for this <3

**Pull request merged**
