### PR TITLE
Update es_mx.json

### PR DESCRIPTION
**Pull request by TheLegendofSaram**
The whole en file translated and fixed some other issues

### CODE REVIEW

**Comment by LostLuma** [comment]
Hi, thank you for the PR!

I just wanted to confirm I've seen this, however I think one translation string will likely change slightly in the next release (no other additions / changes are planned on my side though!), so I'd like to keep this open if you're up to updating it when it's time.

**Comment by TheLegendofSaram** [comment]
Yeah sure, I'll be waiting to translate the update, just make a comment here when is up. That way I'll get a notification

**Review by LostLuma — APPROVED** [review]
I've decided to delay the aforementioned change until later, so this is good to go!

**Comment by TheLegendofSaram** [comment]
okk!

**Pull request merged**
