### PR TITLE
Fix sounds without more specific categories being quieter

### LINKED ISSUE #153: Some audio levels are not matching the vanilla game
Since updating the mod, I noticed that some audio levels do not match the vanilla game anymore.
With my current setup, I always have the master volume set to 3%, while any other category is set to 100%. When using this mod, I can barely hear the UI sound of the game (button clicks, ...), while I can hear them normally without the mod.

### PR DESCRIPTION
**Pull request by LostLuma**
Fixes #153.

I previously wrongly assumed that all sounds played in Minecraft would use one of the other sound categories, and the master volume only exists to control the gain of the audio. As is seen from the linked bug report this is not the case, so the mod has in effect erroneously reduced the volume for these sounds twice instead of once.

For e.g. a master volume of 50% this means sounds playing on the master category were actually played at 25%, with this effect being more and more noticeable at lower master volumes (since the effect is multiplicative).

### CODE REVIEW

**Comment by andreasdc** [comment]
Master volume is general volume for all sounds, right?

**Comment by LostLuma** [comment]
Yes. The complication here was that most sounds in effect have two sound categories (e.g. master and music), but Minecraft wants to obviously only apply one volume transformation if the sound is only played via the master category. Since I did not account for this originally those sounds were quieter.

**Comment by andreasdc** [comment]
Oh nice, I will test that. :) Btw I think with the latest update after long minimalized idle time fps get back to the original value slower than before. Is that possible?

**Comment by LostLuma** [comment]
There has only been [one change](https://github.com/juliand665/Dynamic-FPS/pull/150) to the idle system since its initial release, and all it does is not initialize the whole thing if the user isn't using it. So I don't really see a way for it to be slower.

Generally it's expected for the game to take a second or two (or more on worse systems) to go back to your full frame rate after Dynamic FPS removes the lower FPS limit, and we can't do anything about that without using more resources while in the background or idle. If you think that the mod now takes longer to detect that you are no longer idle you can test this pretty easily by opening the F3 overlay and seeing whether our temporary info line disappears right away or takes a noticeable amount of time.

image

Fwiw it should disappear pretty much immediately, since this check runs at the start of every client tick before the game is rendered (while reducing FPS etc. this is 15 times a second with the mod, even if you run at 1 FPS).

**Pull request merged**
