### PR TITLE
Create all Spanish variants translation files.

### PR DESCRIPTION
**Pull request by Rhbarber**
Spanish translation file, kind of amazed it wasn't created already.

### CODE REVIEW

**Comment by LostLuma** [comment]
Hey, thanks for the translation!

Since you speak the language do you think it's appropriate to copy these same translations for all regions that also use spanish in Minecraft? There's [quite a few variants](https://minecraft.fandom.com/wiki/Language#Languages) (from number 30 all the way to 36 in the list) that would still be without translations otherwise.

**Comment by LostLuma** [comment]
Would be awesome!

**Comment by Rhbarber** [comment]
Should be now done.

**Review by LostLuma — APPROVED** [review]
Looks good, thank you again! 🦫

**Pull request merged**
