### PR TITLE
Improve ru_ru.json

### PR DESCRIPTION
**Pull request by wicivo**
yeah

### CODE REVIEW

**Comment by LostLuma** [comment]
Hey, thanks for the PR! Since this was updated very recently could you weigh in on whether you agree with these changes @RinixGG?

Otherwise this seems good, I'll merge this after we get a response or a few days have passed.

**Comment by wicivo** [comment]
> Hey, thanks for the PR! Since this was updated very recently could you weigh in on whether you agree with these changes @RinixGG?
> 
> Otherwise this seems good, I'll merge this after we get a response or a few days have passed.

👌

**Comment by RinixGG** [comment]
> Hey, thanks for the PR! Since this was updated very recently could you weigh in on whether you agree with these changes @RinixGG?
> 
> Otherwise this seems good, I'll merge this after we get a response or a few days have passed.

Yeah, I agree with these changes, you can merge them.

**Comment by LostLuma** [comment]
Thanks for the reply, will do :)

**Review by LostLuma — APPROVED** [review]

**Pull request merged**
