### PR TITLE
Fix incompatibility with Fabrication's uncap_menu_fps option

### LINKED ISSUE #105: High GPU usage when game is in background
When leaving fps uncapped in Dynamic FPS 3.0.0 the fps skyrockets from 200 to about 2000 (although world rendering is visibly rendered at a lower framerate) causing extremely high GPU usage. even more than when focused. 

https://i.imgur.com/Nk8GAf7.mp4

### PR DESCRIPTION
**Pull request by LostLuma**
Fixes #105 by making Fabrication pull the frame rate limit from Dynamic FPS instead of bypassing us.

### CODE REVIEW

**Comment by LostLuma** [comment]
@JustAlittleWolf if you can please test whether the [fixed version here](https://github.com/juliand665/Dynamic-FPS/actions/runs/6073590754) (inside the `dynamic-fps-artifacts` zip) works for you.

**Comment by JustAlittleWolf** [comment]
Hello, I don't think my message got through haha. Yes the fix works, but I made a suggestion if it wouldn't be better to use `DynamicFPSMod.frameRateTarget()` instead of `DynamicFPSMod.MENU_FRAMERATE_LIMIT` to correctly lower the framerate. At the moment it still shows 60fps in the f3 menu instead of the 10 that the setting is set to.

**Comment by LostLuma** [comment]
Ah! The reason we do not use the frame rate target as the limit is that we *want* the mod to check whether the window has gained focus back 60 times per second, rather than 10 or in some cases one or zero (which would break). That way tabbing back in or clicking on the window will feel very responsive rather than slow. Only 10 of those 60 frames that the game is "rendering" in your case will actually be rendered - the rest is discarded before anything is done.

**Comment by JustAlittleWolf** [comment]
Hmm I just did some testing and as far as I can tell the delay in between focusing the game and the framerate going up again is barely, if at all, noticeable even with a window framerate of 5fps. This does further reduce my gpu background usage from abt 10% (10fps mod setting, 60fps displayed in f3 menu), to about 3-4% (10fps mod setting, 10fps displayed in f3 menu).

I changed the code like so:
```java
callbackInfo.setReturnValue(Math.min(callbackInfo.getReturnValue(), Math.max(DynamicFPSMod.targetFrameRate(), 5)));
```
By changing the constant to lower values like 1 or 2 you can make returning to the game feel noticably slower.

**Comment by LostLuma** [comment]
If it has such a big impact on what I assume is a lower end system it might be worth exploring as an optional setting later (I will write it down), however personally I always switch between screens instead of actually having Minecraft hidden and having the resume take longer did bother me and made me a bit dizzy (maybe I am very prone to this tho) when I tested it a few weeks ago.

**Comment by JustAlittleWolf** [comment]
Thanks, that would be much appreciated!

**Pull request merged**
