### PR TITLE
Update ru_ru.json (Russian)

### PR DESCRIPTION
**Pull request by Alexander317**
Hello! In this PR I've updated the russian translation of your mod to make it more up-to-date.
Feel free to correct me or ask me anything about it, I will answer you and commit changes as soon as I can.

I've been working as a mod translator for quite a while now, so if you like my work, you can consider donating! Thank you! (link in bio)

### CODE REVIEW

**Comment by LostLuma** [comment]
Hi, thank you for the PR!

I'm going to keep this open for now as there will likely be other strings added before the next release, and then ask you if you'd like to add those as well.

**Comment by LostLuma** [comment]
Hello, all features slated for the 3.5.0 release are now available in the `main` branch.

**Comment by LostLuma** [comment]
Well it seems someone else has translated the new strings already (#197), so I will merge this as-is and then the other one :)

**Review by LostLuma — APPROVED** [review]

**Comment by Alexander317** [comment]
Ok, got it!

**Pull request merged**
