### PR TITLE
Add power states system for more configurability

### LINKED ISSUE #77: [SUGGESTION] Multiple FPS targets
Maybe a different FPS target for when the game is unfocused, and another one for when it's not visible?

### LINKED ISSUE #100: Conflict with rrls (RemoveReloadingScreen)
I don't think anything needs to be detailed, you can check everything yourself

https://media.essential.gg/b2da7349-28f9-47c7-d3d3-040d88723100

I also think you know what the cause is, but if not, the problem is [here](https://github.com/juliand665/Dynamic-FPS/blob/main/src/main/java/dynamicfps/mixin/GameRendererMixin.java#L29-L40).

### PR DESCRIPTION
**Pull request by LostLuma**
Hello! I'm finally back with some rather large changes, sadly I got corona so I am very slow ..  
This PR changes quite a few things at once since that was easier to do (and I had nothing else to do while sick 🥲).

---

The main feature is a "power states" system, this is like normal and battery saving mode on a phone, except we have five of these (at the time of writing)! Each option of the mod can be adjusted for each power state (Resolves #77 and #97). Since this is quite a big change I've changed the config format and taken the opportunity to replace toml4j with codecs for an even smaller archive size (55KiB vs ~100KiB before). Also allows configuring the toast feature finally.

FPS reduction now functions slightly different as well. The game is always limited to 60 FPS using the built-in frame rate limiter, and then all unnecessary frames are cancelled (eg. for 1 FPS we cancel 59 out of 60 frames, still have that fast resume!).

Fixes conflict with rrls, resolves #100

And a lot of internal code cleanup that I don't know how to summarize, just hope it is acceptable :)

Sadly we can't use the vanilla named slider options it seems, so I added the note above the FPS target: https://github.com/shedaniel/cloth-config/issues/221

### CODE REVIEW

**Comment by LostLuma** [comment]
Other two issues I've assigned to myself will be separate, figured this is enough at once.

**Comment by juliand665** [comment]
First off, I really like this system! I feel like it solves the problem of configuring different behaviors really elegantly :)

Since you can't label slider values, I wonder if it would make more sense to simply offer a few concrete options:
- 0 FPS (no renders)
- 1 FPS
- maybe a few options from the 2-10 range
- 30 FPS
- 60 FPS
- No reduction

I feel like these would easily cover all use cases while possibly being less fiddly than setting a slider to exactly 0 or 1, though it sucks that we can't display a dropdown or something. We could also filter out nonsensical options like 0/1 fps for `FOCUSED` or `SUSPENDED` (otherwise it would be hard for normal users to undo that change, right?).

I'm also not sure about "precedence" here: if the game is paused in singleplayer, it's `SUSPENDED` even when focused, right? Then when it gets unfocused, I assume it turns into `UNFOCUSED`, but when it's hovered, does it turn back into `HOVERED` or `SUSPENDED`? Maybe this distinction isn't too important, though—food for thought! I also feel like there should maybe be another state for when a UI is open but the game isn't paused (not sure if this would be easy to detect though), where e.g. on a 144Hz monitor you might still want to limit to 60 fps in menus despite the world continuing in the background, or 30 fps on laptops to save power.

**Comment by LostLuma** [comment]
> though it sucks that we can't display a dropdown or something.

Cloth config actually has a dropdown for options, I'll see if it works better. I generally like the thought of having predefined dropdown values like this! 🙂

> We could also filter out nonsensical options like 0/1 fps for FOCUSED or SUSPENDED (otherwise it would be hard for normal users to undo that change, right?).

Those power states are both not configurable (on purpose!) because you either configure the options via the normal options screens, or it would make actually using the normal options screens impossible due to the changed values (at least for video settings, where there is also tens of third-party screens making this harder).

> I'm also not sure about "precedence" here: ...

The `suspended` power state is simply an alternative to `focused`. If you are in a "lower" (at least by the mod's defaults / my intuition) power state it will prefer it. So if you hover back over the game while it's in the pause menu it will turn from `unfocused` to `hovered`, if you tab back in it will switch to `suspended` until you are no longer pausing the game.

> another state for when a UI is open but the game isn't paused

I'm unsure about the .. "half-suspended" state while inside in-game screens at the moment, kinda worried it may look weird to have the animations suddenly be less smooth while you as a player are actually focusing on the Minecraft window as opposed to something else. Can keep it in my notes though as something to do later :)

**Comment by juliand665** [comment]
> Those power states are both not configurable (on purpose!) ...

That makes sense! I should probably have actually built and tried the code before commenting lmao

> If you are in a "lower" (at least by the mod's defaults / my intuition) power state it will prefer it.

Hm yeah I like that. I hope it's clear enough to users, but it's not exactly bound to matter much lol

> kinda worried it may look weird to have the animations suddenly be less smooth

That's fair! I don't think you'd really notice the difference from 144 to 60 when a UI pops up in front though. But we can totally leave this for future work—I don't know how much it'd help and there might well be some annoying edge cases that pop up.

**Comment by LostLuma** [comment]
Alright I've experimented with the "dropdown", however it's more of a mix of a text box which has a dropdown of suggestions which is imo quite awkward to use since you need to erase the entire current "selection" to enter different values (unless I did something catastrophically wrong ofc).

Since I want to get the rrls fix out and am still sick I will simply merge this as-is and look into it again once I can :)

> should probably have actually built and tried the code

Good use-case for me fixing up the actions on this repo, always a download there now 👀

**Pull request merged**
