### PR TITLE
Duplicate language files used for multiple regions

### PR DESCRIPTION
**Pull request by LostLuma**
Same purpose as #120. Will also need to be done for dutch if we get such a translation.
I figure that generally having a not super-specific but working translation is better than none, they can be updated afterwards.

### CODE REVIEW

**Comment by juliand665** [comment]
I suppose the upside is making translators aware of the different regional variants—perhaps they actually know what tweaks to make for a specific region too? The downside is that translators now need to update multiple files for their language, of which they might not know if they started out identical, so they shouldn't just duplicate the same finished file.

Anyway, as a Swiss resident, I can confirm that de-CH needs no changes from de-DE right now: The big one is just `ß` always being written as `ss` here.

**Comment by LostLuma** [comment]
> The downside is that translators now need to update multiple files for their language, of which they might not know if they started out identical, so they shouldn't just duplicate the same finished file.

The original idea of this PR was to just use symlinks so it's obvious you're updating both or need to uncouple them, but it seems that git doesn't really like those (at least on Windows?). It ended up just duplicating the text into the linked copies after committing.

(If it requires non-standard git settings I don't think it's very practical to use symlinks even if it's *possible* to do so.)

**Comment by juliand665** [comment]
Also, now that I'm seeing these translations, I'd suggest a few changes to the German versions (I can just make a fresh PR if you'd like, but I figured this was as good a place as any lol):
- `Setze die Zielbildrate auf -1 um die Bildrate nicht zu reduzieren.` needs a comma before `um`.
- `Ändert die maximale Bildrate damit Minecraft weniger Resourcen im Hintergrund braucht.` similarly needs one before `damit`, and it should be `Ressourcen` with two `s`.
- `Schwebend` feels super weird—is that a term people actually use? I'd probably just use the English `Hover`; I'd expect people to understand that.

**Comment by juliand665** [comment]
> It ended up just duplicating the text into the linked copies after committing.

Ah, that explains things. Unfortunate!

**Comment by LostLuma** [comment]
If you'd like to update the German feel free to push to this branch or merge this and make a PR, I don't think I want to re-open my editor today (or tomorrow either) again though 👀

Somehow it didn't occur to me that you also speak German, that will be useful in case there's more strings in the future as I seem to be pretty rusty from only using it for verbal communication really 🦫

**Comment by juliand665** [comment]
Consider it done! First time pushing to someone else's PR actually.

##### unlimited power

**Pull request merged**
