### PR TITLE
Migrate config to MidnightConfig

### PR DESCRIPTION
**Pull request by wafflecoffee**
This shrinks the jar from 1.2MiB to 360KiB. It accomplishes this by migrating from Cloth Config (which is quite overkill for this mod) to MidnightConfig, by Motschen. This also means the config code will be significantly cleaner.
The main downside to this is that existing configs won't migrate over to the new one (as it uses json instead of toml). I believe this sacrifice is fine, though, since json is easier for data interchange.
I have tested this, and everything works as intended as far as I can tell (even translations).

### CODE REVIEW

**Comment by juliand665** [comment]
Interesting! Getting rid of the cloth dependency would be nice, and MidnightConfig does seem to be significantly cleaner (though I personally dislike those `isReduceFPSWhenUnfocused` etc. names and would probably just get rid of the methods in favor of using the static fields directly). I wish we could keep the TOML format, though, because I rather like it (it's nicer for config editing, too), and it could be backwards-compatible. Any ideas?

**Comment by wafflecoffee** [comment]
> though I personally dislike those isReduceFPSWhenUnfocused etc. names and would probably just get rid of the methods in favor of using the static fields directly

I actually got those names from using Lombok initially, then using IntelliJ's "De-Lombok" option. :P

> I wish we could keep the TOML format, though, because I rather like it (it's nicer for config editing, too), and it could be backwards-compatible. Any ideas?

I agree with the backwards-compatible sentiment (and I'm not all too sure how to do that), but I wouldn't agree with using TOML. JSON is far more standard/common and doesn't require reliance on an obscure external library. It's not exactly *meant* to be changed manually by humans, but that's the point; most users aren't going to be changing their config files by hand anyway.

**Comment by Alvinn8** [comment]
With the simple configuration dynamic fps has, with just three key-value pairs, couldn't a .properties config file work fine? No library is needed for that, and it should be backwards-compatible with the current .toml format as they both use an `=` sign to separate key and value.

**Comment by wafflecoffee** [comment]
I'm going to close this, as it's actually kind of pointless to do this now when QSL will include its own config API, which it looks like will be using either TOML or YAML.

**Comment by juliand665** [comment]
Ooh, that's great to hear! Sorry I haven't had the energy to really work on figuring out a good solution here, but if Quilt comes up with something I'm sure it'll be good.

The only change I could offer would be to not embed cloth config in the jar (which would also help with cross-version compatibility, though people can always drop in an updated version).

**Pull request closed without merging**
