### PR TITLE
Add compatibility for 1.15-Snapshot (19w38a-)

### PR DESCRIPTION
**Pull request by parly**
This PR adds compatibility for `1.15-Snapshot` (`19w38a`-).
This code supports both `1.14.4` and the current snapshot (and hopefully later ones).
I'm sorry if you don't want to support unstable snapshot versions, but I would be happy if you consider accepting this patch :)

### CODE REVIEW

**Comment by juliand665** [comment]
Ooh, thanks for this! I'm not sure what makes `WindowHolder` a compatibility interface though; as far as I can tell it's simply necessary for 1.15+, right?

**Comment by parly** [comment]
Yes. In 19w38a, `MinecraftClient.window` is set to private, so we cannot accessed it directly.
The getter method is defined instead, but it doesn't exist in 1.14.4.
So I made `WindowHolder` interface to read `window` indirectly to work on both versions.

Anyway, thank you for merging this PR!

**Comment by juliand665** [comment]
Interesting; I couldn't find any `getWindow()` method in 19w38b, so I kept the mixin despite not really caring about backwards compatibility (not like I'll be making any changes I should backport anytime soon).

**Comment by parly** [comment]
Ah, after some research, I found that the getter method in 19w38b is unnamed yet in the current yarn. It's `method_22683()`. If we don't need to worry about backward compatibility, using that method directly might be better.
Sorry for the confusion.

**Comment by juliand665** [comment]
I see! Thanks for investigating. I guess I'll keep the mixin for now and switch back to the getter whenever the next update is needed.

**Pull request merged**
