### PR TITLE
Device battery integration

### PR DESCRIPTION
**Pull request by LostLuma**
Partial (?) resolution to #181.

Allows the mod to track device battery levels and statuses.
Using this I've added some new and adapted some of our existing features:
- Add a new optional power state while on battery
  - For now only the frame rate target is configurable here
  - Other settings don't make sense since the user is active
- Add condition to only enable idling when on battery
  - This is enabled by default with a timeout of 5 minutes to conserve battery
- Add battery notifications
  - A toast will appear when the battery is below 10%, or is now (dis)charging
- Add optional battery info on in-game HUD
  - This is enabled by default when the battery is below 10% 

To do this I [wrote a small library](https://github.com/LostLuma/battery) which wraps the [starship battery](https://crates.io/crates/starship-battery) crate for reliable cross-platform battery info.
Since this is (obviously) not fully written in Java having the dynamic library on hand is required for using these new features.

In total there is ~2MiB of natives for Linux, MacOS, and Windows on both aarch64 and amd64.
Since this would make the mod kind of explode in size the matching library is downloaded and verified on first startup, then cached.

Disabling the battery tracker will ensure the mod never downloads the library.
Given the circumstances I'm not sure this feature should stay enabled by default, even if it would be the most useful for end users.

---

The new assets were made by @Pixaurora and I have decided to not license them under the MIT license for now at least, but they may be released in the mod even if I decide to stop maintaining it at some point.

### CODE REVIEW

**Comment by juliand665** [comment]
This is a really cool project, love that you're working with rust too! I do think it needs to be disabled by default since it downloads executables from the internet and runs them, even if it's from a server you personally control.

On that note, what happens if your server stops running or is unreachable? How much would this annoy people who (currently or permanently) can't download the file?

Maybe we could provide instructions for people who want to download & validate the native personally, as well as an option to prevent the mod from performing the download itself?

**Comment by LostLuma** [comment]
> even if it's from a server you personally control.

The reason I thought this may be fine is that the library knows the sha512 of the file it's downloading ahead of time (it's embedded in the jar), so you'd have a very hard time installing something else even if you gain control the server. But maybe we can reevaluate this later after getting more feedback on this feature instead of releasing it to everyone at once.

> Maybe we could provide instructions for people who want to download & validate the native personally

And I had not thought of actually publishing them elsewhere, but I suppose I will just include them in the GitHub release and amend the description here with some instructions tomorrow.

> as well as an option to prevent the mod from performing the download itself?

If the default settings disable this feature it'll also not download the file itself unless instructed to by the user, so you'd have the option of doing so yourself before enabling it. I suppose the toggle needs a little blurb with this info though.

Glad you seem to like the changes in general though 🙂

**Comment by juliand665** [comment]
> the library knows the sha512 of the file it's downloading ahead of time
Oh, I didn't realize! With this, I think it's actually pretty safe after all. The only way I could think of to trick it would involve the JVM, at which point you've already lost anyway (attacker would have to have their java code running on the same machine).

> you'd have the option of doing so yourself before enabling it
My thought was that this feels a little fragile, since mod updates could then cause it to instead download & run a different JAR. Hence the option to (effectively) configure downloading separately from running.

**Comment by LostLuma** [comment]
I've now changed a few things based on feedback:
- The battery features are now disabled by default so using / testing them is opt-in, at least for now
- Added a new advanced configuration option that allows disabling any sort of downloading even if the feature is on
- Added a small step-by-step guide to the `GitHub/` folder that is linked in the readme on how to install the library yourself
- Fixed an issue causing battery notifications in wrong situations

**Comment by juliand665** [comment]
haven't exactly perused the code but the changes LGTM now!

**Comment by LostLuma** [comment]
Awesome :) I will merge this then so we can get the translation PRs updated for a future release with this.  
Hopefully there will be little to no changes still needed to release this (I have asked a few people to test it).

**Pull request merged**
